### ISSUE TITLE
certificate issue

### ISSUE THREAD

**Issue by iicsanjeev** [callstats-io/node-webrtc-basic-app#3]
Hi Karthik,
I am getting following errors while running app:

> sample-webrtc-app@1.0.0 start /Users/sanjeevkumar/Downloads/node-webrtc-basic-app
> node index.js

_tls_common.js:134
      c.context.setKey(key, passphrase);
                ^

Error: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch
    at Object.createSecureContext (_tls_common.js:134:17)
    at Server (_tls_wrap.js:868:27)
    at new Server (https.js:62:14)
    at Object.createServer (https.js:84:10)
    at Object.<anonymous> (/Users/sanjeevkumar/Downloads/node-webrtc-basic-app/index.js:30:25)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sample-webrtc-app@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sample-webrtc-app@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sanjeevkumar/.npm/_logs/2018-11-23T11_21_37_829Z-debug.log

I followed following instructions while creating server.crt, server.key 

https://brianflove.com/2014/12/01/self-signed-ssl-certificate-on-mac-yosemite/

if I follow instructions mentioned in aforementioned link then I can generate both server.crt and server.key files but how to get ca.crt certificate ?

**Comment by karthikbr82** [comment]
Use this command to generate certificates,
openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout server.key -out server.crt -passin pass:v2ZIZj2jKUap -subj '/CN=localhost/O=Local/C=FI'
cp server.crt ca.crt

**Comment by karthikbr82** [comment]
This is also not maintained any more, chkout new demo app - https://github.com/callstats-io/webrtc-demoapp
